### ISSUE TITLE
ask deploy gives error

### ISSUE THREAD

**Issue by grivap** [alexa/skill-sample-nodejs-adventure-game#69]
Followed all the steps, and when I typed 'ask deploy' in the terminal, I get this error:

**[Error]: Failed to deploy. Please ensure current working directory is the root of your skill project.**

The config file wasn't created, so tried to create one manually, but that didn't work either.

**Comment by error404notfound** [comment]
What project are you trying to deploy? ( I am having similar problems with deploy but I think that they are to do with my AWS account now ) 

 have you tried to do deploy with the debug flag? 
ask deploy --debug

it might highlight where it's trying to look and what it can't find.

**Comment by grivap** [comment]
I was trying to deploy this skill-sample-nodejs-adventure-game project. I think I had to follow the [instructions](https://github.com/alexa/skill-sample-nodejs-adventure-game/tree/master/instructions) to fix the error, which is what I am currently working on.

**Comment by supriyodey** [comment]
i'm getting the same error..what's the solution?

**Comment by error404notfound** [comment]
I am still getting the same error with this one as well, but I am able to deploy other examples. 
Are you able to deploy the high low game sample or a  the hello world? 

 There may like girvap says be something missing from the existing code that you add in with the steps. all though from a quick glance it looks like the steps guide you using the web interface, 

its strange that in this case the  debug flag is producing no other information  just the same error.

**Comment by franklin-lobb** [comment]
for the deploy command to work, you will need to be the directory with the skill.json file (the project root).  From there, there needs to be an .ask/config file and the code in the lambda/custom folder (or where specified in the skill.json file).  Finally there needs to be a corresponding interaction model in the models folder for each locale included in the skill.json file.

I'm working on an update to the sample and part of the tests include being able to deploy via the ask-cli tool.  If there's a fix required to make that work, I'll include it.  If you're able to deploy other skills using the cli, then the issue is definitely with this skill and not your setup.  If you cannot deploy the fact skill (for example), I would check back on your cli setup.

**Comment by franklin-lobb** [comment]
The code has been updated such that it deploys successfully now.  If you're still having trouble, please re-open the issue.
